# A skeleton sysroot specification file.

[libffi]
version = "0.0.0"

[OpenSSL]
version = "0.0.0"

[Python]
version = "0.0.0"

[PyQt]
version = "0.0.0"
installed_modules = []


[PyQtPurchasing]
version = "0.0.0"

[PyQtWebEngine]
version = "0.0.0"

[QScintilla]
version = "0.0.0"

[Qt]
version = "0.0.0"

[SIP]
version = "0.0.0"
module_name = ""

[zlib]
version = "0.0.0"